Feature/email login
upathorg/Backend-in-Node-And-Database pull request #20
Opened 2020-09-21 23:16 UTC by fungainyatanga

Hey Guy 
Anitha has an active pull request ahead of mine, **### so please do not merge yet** but I just want to make sure you have time to review
The best way is to pull the branch if you use postman here are the requests 
**Signup= http://localhost:5000/signup**  
body{
	"email": "test123@gmail.com",
         "username": "test123",
	"password": "admin123"
}
Response: will just be a success user created. 

**Login=http://localhost:5000/login**
body{
"email": "test123@gmail.com",
"password": "admin123"
}
Login will generate a token in the response
 You can create any user just wanted to give an example

2020-09-22 11:01 UTC, justmic007 requested changes

2020-09-22 11:01 UTC, justmic007 commented on src/auth/authHandlers.ts
> +export const validateData = (data: { email?: any; username?:any; password?: any }) => {
I think email, username and password types should be `string` and not `any`. It should convert whichever data type supplied to a string

2020-09-22 11:07 UTC, justmic007 commented
Bro,

I just tested with Postman. It works, though I left some comments on your
PR if you can look into it


On Tue, Sep 22, 2020 at 12:16 AM KEVIN <notifications@github.com> wrote:

> Hey Guy
> Anitha has an active pull request ahead of mine, *### so please do not
> merge yet* but I just want to make sure you have time to review
> The best way is to pull the branch if you use postman here are the requests
> *Signup= http://localhost:5000/signup <http://localhost:5000/signup>*
> body{
> "email": "test123@gmail.com",
> "username": "test123",
> "password": "admin123"
> }
> Response: will just be a success user created.
>
> *Login=http://localhost:5000/login <http://localhost:5000/login>*
> body{
> "email": "test123@gmail.com",
> "password": "admin123"
> }
> Login will generate a token in the response
> You can create any user just wanted to give an example
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/upathorg/Backend-in-Node-And-Database/pull/20
> Commit Summary
>
>    - local login for email and password
>    - login things
>    - complete signup and login passport local
>    - changes to the getuser query
>    - resolve conflict
>    - add username
>    - cleanup remove unnecessary console.logs
>    - more cleanup
>
> File Changes
>
>    - *M* package-lock.json
>    <https://github.com/upathorg/Backend-in-Node-And-Database/pull/20/files#diff-32607347f8126e6534ebc7ebaec4853d>
>    (8)
>    - *M* package.json
>    <https://github.com/upathorg/Backend-in-Node-And-Database/pull/20/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2>
>    (1)
>    - *M* src/auth/authHandlers.ts
>    <https://github.com/upathorg/Backend-in-Node-And-Database/pull/20/files#diff-88cdddb197d653fe5e671955e837b6d7>
>    (29)
>    - *M* src/auth/googlePassport.ts
>    <https://github.com/upathorg/Backend-in-Node-And-Database/pull/20/files#diff-f0537b91afac6de9b1b110db3f7cae16>
>    (1)
>    - *A* src/auth/localPassport.ts
>    <https://github.com/upathorg/Backend-in-Node-And-Database/pull/20/files#diff-786913c86976987d95fb422fabedee81>
>    (78)
>    - *M* src/endpoints/users/queries.ts
>    <https://github.com/upathorg/Backend-in-Node-And-Database/pull/20/files#diff-456ef498fab947ab7388c633c50eb318>
>    (2)
>    - *M* src/server.ts
>    <https://github.com/upathorg/Backend-in-Node-And-Database/pull/20/files#diff-916156c481141bfcd08c6ae40ce10e00>
>    (47)
>    - *M* yarn.lock
>    <https://github.com/upathorg/Backend-in-Node-And-Database/pull/20/files#diff-8ee2343978836a779dc9f8d6b794c3b2>
>    (51)
>
> Patch Links:
>
>    -
>    https://github.com/upathorg/Backend-in-Node-And-Database/pull/20.patch
>    - https://github.com/upathorg/Backend-in-Node-And-Database/pull/20.diff
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/upathorg/Backend-in-Node-And-Database/pull/20>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIVBV7RTI2J4IXUILGC3YO3SG7NFNANCNFSM4RVDBJQQ>
> .
>

2020-09-23 19:13 UTC, fungainyatanga commented on src/server.ts
> +app.post('/signup', Signup);
So I cant add redirect to login because page doesn't exist the Ui will have to handle once signup has occurred

2020-09-23 23:39 UTC, justmic007 approved these changes

2020-09-24 00:22 UTC, anithaamarnath commented
It's working perfectly

2020-09-24 00:23 UTC, anithaamarnath approved these changes

2020-09-24 00:32 UTC, merged