Feature/education endpoint
upathorg/Backend-in-Node-And-Database pull request #23
Opened 2020-09-29 13:01 UTC by justmic007

- [X] generate education migration table
- [X] add db drivers or services
- [X] add education CRUD to resolvers
- [X] add schema and type definitions for education endpoint
- [X] add education table to user record aggregation using joins

2020-09-29 17:51 UTC, anithaamarnath approved these changes
its works perfectly on my local

2020-10-01 14:09 UTC, fungainyatanga commented on src/interfaces/queryInterfaces.ts
> +  skills?: string
Question: For skills do we not need this to be an **<List>**  since a users can have multiple skills for example. 
levelofeducation: "Bachelors",
University: "university of code"
Field: "Computer Science",
Skillls: databases, javascript, c++, data structures etc

2020-10-01 14:19 UTC, fungainyatanga commented on src/endpoints/users/queries.ts
>    getUserRecordByEmail: async (email: string) => {
Remove password from the response

2020-10-01 14:23 UTC, fungainyatanga requested changes
Everything looks good just review my comments,

2020-10-02 11:48 UTC, justmic007 commented on src/interfaces/queryInterfaces.ts
> +  skills?: string
**Valid question.**

I just googled how we can store Objects/Arrays in knex/postgres and found that it does not have a native way of storing such. What is available is **table.specificType('skills', 'json[]')** or **table.specificType('skills', 'jsonb[]')** which i tried at this time, but yet to figure out how we can declare the skills field to hold the value of an array of strings like this **string[]** on the Schema part of the graphql. Hence, could not successfully make a post.

**Alternatively**, we can allow the Client side to handle it. Meaning if we have various skills listed, as the user is selecting from the pool of skills listed, the fronted can store them in a array say Skills and then stringify it into a string like the below before sending it as a payload to the backend

i.e after selecting skills, the user array of skills will look like this:
     **`skills = ["data structures", "algorithms", "software engineering"]`**

and to stringify, will do something like this:
     **`skills.toString()`**

and will return something like this
    **`result = "data structures,algorithms,software engineering"`**

before sending it as part of the payload at the point of createEducation


What is your take?

2020-10-02 11:50 UTC, justmic007 commented on src/endpoints/users/queries.ts
>    getUserRecordByEmail: async (email: string) => {
Removed from the resolver end

2020-10-02 13:01 UTC, fungainyatanga commented on src/interfaces/queryInterfaces.ts
> +  skills?: string
I agree lets have the client side handle converting the [] into a skills string but i think as best practice if it alot involved for them we might need to rethink it. 
so Lets do the **Alternatively**

2020-10-02 13:03 UTC, fungainyatanga approved these changes

2020-10-02 14:15 UTC, justmic007 commented on src/interfaces/queryInterfaces.ts
> +  skills?: string
Sure

2020-10-02 14:15 UTC, merged